name: Linux-s390x

on:
  workflow_dispatch:
  push:
    branches: [ "s390x" ]
    paths-ignore:
      - 'docs/**'
      - STATUS
      - CHANGES
      - changes-entries/*
    tags:
      - 2.*
  pull_request:
    branches: [ "s390x" ]
    paths-ignore:
      - 'docs/**'
      - STATUS
      - CHANGES
      - changes-entries/*

jobs:
  run_script:
    runs-on: self-hosted
    container:
      image: linux-s390x:latest
      platform: linux/s390x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        run: |
          chmod +x ./Docker/script.sh
          ./Docker/script.sh
